from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Protocol

from opcua_tui.domain.models import (
    ConnectParams,
    DataValueView,
    NodeAttributes,
    NodeRef,
    SessionInfo,
    SubscriptionValueUpdate,
)


class OpcUaClientPort(Protocol):
    async def start_subscription_stream(
        self, on_update: Callable[[SubscriptionValueUpdate], Awaitable[None]]
    ) -> None: ...
    async def stop_subscription_stream(self) -> None: ...
    async def subscribe_value(self, node_id: str) -> str: ...
    async def unsubscribe_value(self, node_id: str) -> None: ...
    async def connect(self, params: ConnectParams) -> SessionInfo: ...
    async def disconnect(self) -> None: ...
    async def browse_children(self, node_id: str | None) -> list[NodeRef]: ...
    async def read_attributes(self, node_id: str) -> NodeAttributes: ...
    async def read_value(self, node_id: str) -> DataValueView: ...
    async def write_value(
        self, node_id: str, value_text: str, variant_hint: str | None = None
    ) -> None: ...
